### PR TITLE
Fixed geojson serialization bug. Reversing an array in place corrupts data and makes invalid polygons

### PR DESCRIPTION
**Pull request by alex2512**

### CODE REVIEW

**Comment by FObermaier** [comment]
Does this refer to any open issue?
A unit test is needed.

**Comment by airbreather** [comment]
> Does this refer to any open issue?

The claim is that this relates to #114.  While I agree that reversing the sequence in-place is rude and potentially problematic, and that it should definitely be fixed, it shouldn't ever cause polygons to become outright **invalid** unless there is a different, unrelated bug in [`CoordinateSequences.Reverse`](https://github.com/NetTopologySuite/NetTopologySuite/blob/v2.5.0/src/NetTopologySuite/Geometries/CoordinateSequences.cs#L14-L26).

For what it's worth, I agree that this is the correct change, but...

>  A unit test is needed.

Yes, absolutely.

**Comment by airbreather** [comment]
It also seems to cause 4 of the existing tests to fail — which is interesting, because I think it means that they were only passing because they **expected** the input sequences to be modified in this rude way.

**Comment by airbreather** [comment]
> It also seems to cause 4 of the existing tests to fail — which is interesting, because I think it means that they were only passing because they expected the input sequences to be modified in this rude way.

I have pushed a change to `develop` that makes sure to expect the geometries to be saved with the correct ring orientation.  This test passes on `develop`, and after merging it to the incoming branch (which I have also done), it **also** allows the existing tests to continue to pass after this change, as I believe that they should.

As @FObermaier said above, however, I would still want to see an automated test that demonstrates the "corrupts data and makes invalid polygons" part of this.  It is **not at all** clear to me why this change would fix an issue like that, so if we were to merge it as-is without such a test, then I worry that a future "obvious" change might break that again.

**Comment by FObermaier** [comment]
This has been merged by other means. Thanks

**Comment by pmohr-uwa** [comment]
@airbreather @FObermaier 
> As @FObermaier said above, however, I would still want to see an automated test that demonstrates the "corrupts data and makes invalid polygons" part of this. It is **not at all** clear to me why this change would fix an issue like that, so if we were to merge it as-is without such a test, then I worry that a future "obvious" change might break that again.

I managed to reproduce this corruption bug in 3.0.0.  It's fixed in 4.0.0

When the winding order is reversed, the array sparsePolygon wasn't reversed.  Instead, the coordinates in each element were swapped.  This corrupts any polygon that shares instances Coordinate contained in Geometry.Coordinates.

[Program.txt](https://github.com/user-attachments/files/15908976/Program.txt)

**Pull request closed without merging**
