### PR TITLE
Custom coordinates formatting

### PR DESCRIPTION
**Pull request by bstordrup**
Made some changes in the GeoJsonSerializer and in the GeometryConverter class that allows for a different formatting of the coordinates property on the Geometry classes in the json file.

For example, you can specify Formatting.Indented for the json in general, but put in a JsonSerializerSettings instance with Formatting.None for the writing of coordinates property.

Changes in GeoJsonSerializer:
* New CreateDefault overload that takes a secondary JsonSerializerSettiings instance.
* Added a parameter to the AddGeoJsonConverters class (default null) and passing this to the constructor of the GeometryConverter class.
* Added a constructor overload of GeometryConverter class taking in the extra JsonSerializerSettings instance and stores this in a member field.
* Added functions for backing up serializer settings and applying serializer settings.
* In the WriteJson function, when coordinates are written, then first backup the serializer settings from the writer. next apply the custom serializer settings if found and after writing coordinates, the backup of serializer settings are applied back to the writer

### CODE REVIEW

**Comment by bstordrup** [comment]
@FObermaier, could you have a look?

**Comment by bstordrup** [comment]
@airbreather, could you have a look?

**Comment by airbreather** [comment]
I'll take a look at it, but in the meantime, can you please show examples of the kind of usage that this enables?  Either in new automated tests (ideal) or just on this PR.

**Comment by bstordrup** [comment]
I have uploaded a sample geojson file formatted with this feature as well as a screen snip of it. Please have a look. The folder with the files are public available via the link.

https://drive.google.com/drive/folders/1QBpc_FkE4evSQfKsyKHhEMJkeZduS7Ws?usp=sharing

**Review by airbreather — APPROVED** [review]
LGTM (with some minor nits that I'll just fix after merging).  Sorry about the delay.

**Pull request merged**
