### PR TITLE
fix issue crs was not deserialized in feature

### PR DESCRIPTION
**Pull request by seloger-tomtom**
issue #14

### CODE REVIEW

**Comment by airbreather** [comment]
:question: should we maybe tweak that `default` case to make sure that we *actually* skip looking at extended objects that might happen to have properties with names that match our recognized list?

**Comment by airbreather** [comment]
💭 it seems odd to me to have `feature.Attributes["name"] =="urn:ogc:def:crs:OGC:1.3:CRS84"`, since that sounds (to me) a lot more like it's the name of the **feature** rather than the name of the feature's CRS.

I'm wondering if it might make more sense to just add the `ICRSObject` object directly as a `"crs"` attribute of the feature?  Then we'd have `((CRSBase)feature.Attributes["crs"]).Properties["name"]`... hmm, actually, that's also not very compelling.

Maybe prefix the property keys with something like `"crs-"` so that the feature we return would have `feature.Attributes["crs-name"] == "urn:ogc:def:crs:OGC:1.3:CRS84"`?

@FObermaier thoughts about how best to store the data from the `ICRSObject` on the feature's attributes table?  Also, I don't have merge permissions on most of the IO projects, so I won't actually be able to bring this to a conclusion.

**Comment by FObermaier** [comment]
`crs` used to be a valid type for GeoJSON. It could either be an `Authority:Code` tuple or an urn, like in the example above.

In the [current spec](https://tools.ietf.org/html/rfc7946#appendix-B.1) it states that `crs` has been removed. We should start to treat it as a string and don't bother any more with it.

**Comment by seloger-tomtom** [comment]
I was gonna ask you because in the old version it worked that way.

if crs has been removed we could ignore it like other unmanaged prpoperties

**Comment by airbreather** [comment]
> don't bother any more with it

OK, so the desired fix is to just make sure that we fully skip nested complex objects instead of what the current code does, which appears to actually dig into their own properties.

@seloger-tomtom would you be OK with doing that?  If not, I can try to do it tonight.

**Comment by seloger-tomtom** [comment]
let me 5 min, i'm doing this :)

**Comment by airbreather** [comment]
Merged, thank you for your contribution

**Comment by FObermaier** [comment]
@sl-tomtom, as you have contributed to this project prior to us enforcing a CLA I'm asking you if you have any objections if we change the license for `NetTopologySuite.IO.GeoJSON` from LGPL 2.1 or later to either MIT or BSD 3?

**Comment by sl-tomtom** [comment]
> @sl-tomtom, as you have contributed to this project prior to us enforcing a CLA I'm asking you if you have any objections if we change the license for `NetTopologySuite.IO.GeoJSON` from LGPL 2.1 or later to either MIT or BSD 3?

It's good for me

**Pull request merged**
